# Generated by Django 6.0.7 on 2026-07-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pontowifi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontowifi',
            name='codigo',
            field=models.CharField(default='COD001', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
