# Generated by Django 6.0.7 on 2026-07-31 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pontowifi_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problema', models.CharField(max_length=200)),
                ('responsavel', models.CharField(max_length=100)),
                ('data_abertura', models.DateField()),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Aberta', 'Aberta'), ('Em andamento', 'Em andamento'), ('Concluída', 'Concluída')], max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pontowifi')),
            ],
        ),
    ]
