# Generated by Django 6.0.7 on 2026-07-31 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_manutencao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manutencao',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
